### PR TITLE
fix CocoIterator being loaded even though we're not using COCO datase…

### PR DESCRIPTION
**Pull request by sorinpanduru**

### CODE REVIEW

**Comment by hgaiser** [comment]
I agree with the change, but this change will break the [examples](https://github.com/delftrobotics/keras-retinanet/blob/master/examples). Also to be consistent, can you also remove the VocIterator and make the appropriate changes in the examples?

**Comment by sorinpanduru** [comment]
Hi!
I updated the examples scripts too.

**Comment by hgaiser** [comment]
Thanks, almost there. It's used in the jupyter notebooks and the COCO evaluation script as well.

**Comment by sorinpanduru** [comment]
Hello,
the notebooks and the coco eval scripts use a FQN when instantiating the CocoIterator class... there's no need to do the imports there too.

**Comment by hgaiser** [comment]
Eventhough they use a FQN, if you don't import it in the `__init__.py` it will not automatically import that submodule. Try it out, I thought it would work too but when I tested it, it doesn't work.

**Comment by hgaiser** [comment]
If you import it as `from keras_retinanet.preprocessing.coco import CocoIterator`, then it also needs to be referenced as `CocoIterator`. Currently it is being referenced as `keras_retinanet.preprocessing.coco.CocoIterator`.

**Comment by hgaiser** [comment]
Awesome, looks good.

**Pull request merged**
